// <auto-generated />
using System;
using Achievo.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Achievo.Infrastructure.Migrations
{
    [DbContext(typeof(AchievoDbContext))]
    [Migration("20251021171314_AddedTaskPoints")]
    partial class AddedTaskPoints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Achievo.Infrastructure.Models.Models.TaskTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("EstimatedDuration")
                        .HasColumnType("time");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaskTemplates");
                });

            modelBuilder.Entity("Achievo.Infrastructure.Models.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("Ind_UserId");

                    b.HasIndex("TotalPoints")
                        .HasDatabaseName("Ind_UserPoint");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Achievo.Infrastructure.Models.Models.UserPoints", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("Ind_UserId_CreatedAt");

                    b.ToTable("UserPoints");
                });

            modelBuilder.Entity("Achievo.Infrastructure.Models.Models.UserTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssignedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("pointsAwarded")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DueAt")
                        .HasDatabaseName("Ind_DueAt");

                    b.HasIndex("AssignedUserId", "Status", "AssignedAt")
                        .HasDatabaseName("Ind_AssignedUserId_Status_AssignedAt");

                    b.ToTable("UserTasks", t =>
                        {
                            t.Property("AssignedUserId")
                                .HasColumnName("UserTask_AssignedUserId");

                            t.Property("AssignedUserName")
                                .HasColumnName("UserTask_AssignedUserName");
                        });
                });

            modelBuilder.Entity("Achievo.Infrastructure.Models.Models.UserTask", b =>
                {
                    b.OwnsOne("Achievo.Shared.Reference", "AssignedUser", b1 =>
                        {
                            b1.Property<Guid>("UserTaskId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("AssignedUserId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("AssignedUserName");

                            b1.HasKey("UserTaskId");

                            b1.ToTable("UserTasks");

                            b1.WithOwner()
                                .HasForeignKey("UserTaskId");
                        });

                    b.OwnsOne("Achievo.Shared.Reference", "TaskTemplate", b1 =>
                        {
                            b1.Property<Guid>("UserTaskId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("TaskTemplateId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("TaskTemplateName");

                            b1.HasKey("UserTaskId");

                            b1.ToTable("UserTasks");

                            b1.WithOwner()
                                .HasForeignKey("UserTaskId");
                        });

                    b.Navigation("AssignedUser")
                        .IsRequired();

                    b.Navigation("TaskTemplate")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
